globus:
  globus_endpoints:
    spot832:
      root_path: /
      uri: spot832.lbl.gov
      uuid: 44ae904c-ab64-4145-a8f0-7287de38324d
      name: spot832

    data832:
      root_path: /data
      uri: data832.lbl.gov
      uuid: 75b478b2-37af-46df-bfbd-71ed692c6506
      name: data832

    data832_raw:
      root_path: /data/raw
      uri: data832.lbl.gov
      uuid: 75b478b2-37af-46df-bfbd-71ed692c6506
      name: data832_raw

    data832_scratch:
      root_path: /data/scratch/globus_share
      uri: data832.lbl.gov
      uuid: 75b478b2-37af-46df-bfbd-71ed692c6506
      name: data832_scratch

    alcf832_raw:
      root_path: /data/raw
      uri: alcf.anl.gov
      uuid: a89365da-e614-48fe-9ee5-f5e1698a68c8 # 55c3adf6-31f1-4647-9a38-52591642f7e7
      name: alcf_raw

    alcf832_scratch:
      root_path: /data/scratch
      uri: alcf.anl.gov
      uuid: a89365da-e614-48fe-9ee5-f5e1698a68c8 # 55c3adf6-31f1-4647-9a38-52591642f7e7
      name: alcf_scratch

    alcf_eagle832:
      root_path: /IRIBeta/als/example
      uri: alcf.anl.gov
      uuid: 05d2c76a-e867-4f67-aa57-76edeb0beda0
      name: alcf_eagle832

    alcf_home832:
      root_path: / #alcf /home/username
      uri: alcf.anl.gov
      uuid: 9032dd3a-e841-4687-a163-2720da731b5b
      name: alcf_home832

    nersc_alsdev:
      root_path: /global/homes/a/alsdev/test_directory_xchong/
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc_alsdev

    nersc832_alsdev_raw:
      root_path: /global/cfs/cdirs/als/data_mover/8.3.2/raw
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_raw

    nersc832_alsdev_scratch:
      root_path: /global/cfs/cdirs/als/data_mover/8.3.2/scratch
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_scratch

    nersc832_alsdev_pscratch_raw:
      root_path: /pscratch/sd/a/alsdev/8.3.2/raw
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_pscratch_raw

    nersc832_alsdev_pscratch_scratch:
      root_path: /pscratch/sd/a/alsdev/8.3.2/scratch
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_pscratch_scratch

    nersc832_alsdev_recon_scripts:
      root_path: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_reconstruction_scripts
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_recon_scripts

    nersc832:
      root_path: /global/cfs/cdirs/als/data_mover/8.3.2
      uri: nersc.gov
      uuid: df82346e-9a15-11ea-b3c4-0ae144191ee3
      name: nersc832

    nersc7012:
      root_path: /global/cfs/cdirs/als/gsharing/data_mover/7012
      uri: nersc.gov
      uuid: df82346e-9a15-11ea-b3c4-0ae144191ee3
      name: nersc7012

    data7012:
      root_path: /
      uri: hpc.lbl.gov
      uuid: 639c49be-604f-423c-9c5d-82a53afe1bf1
      name: data7012

  globus_apps:
    als_transfer:
      client_id: ${GLOBUS_CLIENT_ID}
      client_secret: ${GLOBUS_CLIENT_SECRET}

harbor_images832:
  recon_image: tomorecon_nersc_mpi_hdf5@sha256:cc098a2cfb6b1632ea872a202c66cb7566908da066fd8f8c123b92fa95c2a43c
  multires_image: tomorecon_nersc_mpi_hdf5@sha256:cc098a2cfb6b1632ea872a202c66cb7566908da066fd8f8c123b92fa95c2a43c

ghcr_images832:
  recon_image: ghcr.io/als-computing/microct:master
  multires_image: ghcr.io/als-computing/microct:master

prefect:
  deployments:
  - type_spec: new_file_832
    uuid: ccf2cb27-d4f8-420b-8115-a5036c69b1da

scicat:
  jobs_api_url: https://dataportal.als.lbl.gov/api/ingest/jobs
