globus:
  globus_endpoints:
    spot832:
      root_path: /
      uri: spot832.lbl.gov
      uuid: 44ae904c-ab64-4145-a8f0-7287de38324d
    
    data832:
      root_path: /data
      uri: data832.lbl.gov
      uuid: 75b478b2-37af-46df-bfbd-71ed692c6506

    nersc:
      root_path: /global/cfs/cdirs/als/data_mover
      uri: nersc.gov
      uuid: df82346e-9a15-11ea-b3c4-0ae144191ee3

  globus_apps:
    als_transfer:
      client_id: ${GLOBUS_CLIENT_ID}
      client_secret: ${GLOBUS_CLIENT_SECRET}

prefect:
  deployments:
    - type_spec: new_file_832
      uuid: ccf2cb27-d4f8-420b-8115-a5036c69b1da

scicat:
  jobs_api_url: https://dataportal.als.lbl.gov/api/ingest/jobs



