name: splash globus flows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.5
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.5
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir flake8 pytest
        pip install --no-cache-dir .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Build MkDocs site
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: mkdocs gh-deploy -f docs/mkdocs/mkdocs.yml --force
